-
  hosts: all
  sudo: true
  vars:
    apt_packages:
      - git
      - nodejs
      - nginx
    app_path: /mnt/app
  tasks:
    - shell: cat /etc/hosts
      register: hosts_contents

    - debug: var=hosts_contents

    - shell: echo "/etc/hosts contains an entry for google"
      when: hosts_contents.stdout.find('google') != -1
