-
  hosts: all
  sudo: true
  vars:
    apt_packages:
      - git
      - nodejs
      - nginx
    node_path: /usr/bin/nodejs
    app_path: /mnt/app
  tasks:
    - name: install apt packages
      apt: name={{item}} state=latest update_cache=yes
      with_items: apt_packages

    - name: make sure code is on the box
      copy: src=../app.js dest=/mnt

    - name: install service
      template: src=app.conf dest=/etc/init

    - name: start services
      service: name={{item}} state=restarted
      with_items:
        - nginx
        - app
