-
  hosts: all
  sudo: true
  vars:
    apt_packages:
      - git
      - nodejs
      - nginx
  tasks:
    - name: install apt packages
      apt: name={{item}} state=latest update_cache=yes
      with_items: apt_packages

    - name: make sure code is on the box
      copy: src=../app.js dest=/mnt

    - name: ensure upstart script for app is in place
      copy: src=../app.conf dest=/etc/init

    - name: start app
      service: name=app state=started
