-
  hosts: all
  sudo: true
  vars:
    apt_packages:
      - git
      - node
      - nginx
    app_path: /mnt/app
  tasks:
    - name: install apt packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items: apt_packages

    - name: make sure code is on the box
      copy: src=../app.js dest=/mnt

    - name: find node path
      command: which node
      register: node_path

    - name: install service
      template: src=../app.conf dest=/etc/init

    - name: start services
      service: name={{ item }} state=started
      with_items:
        - nginx
        - app
