-
  hosts: all
  sudo: true
  vars:
    conditional: true
    apt_packages:
      - git
      - nodejs
      - nginx
  tasks:
    - name: install apt packages
      apt: name={{item}} state=latest update_cache=yes
      with_items: apt_packages
      when: conditional == true

    - include: other.yml
      when: conditional == false
